require("configs.flutter-tools").setup()
require("configs.mason").setup()
require("configs.neo-tree").setup()
-- require("configs.null-ls").setup()
require("configs.hop").setup()
require("configs.nvim-surround").setup()
