[env]
_.file = '.env'

[tools]
node = "lts"
python = "latest"
uv = "latest"
"npm:git-cz" = "latest"
"npm:mcp-hub" = "latest"
"npm:vercel" = "latest"
"npm:@openai/codex" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:wrangler" = "latest"
"npm:mmcp" = "latest"
"npm:tsx" = "latest"
"npm:dotenv-cli" = "latest"
"npm:memvid-cli" = "latest"
"npm:neonctl" = "latest"
"pipx:whisply" = "latest"
"pipx:mlx-whisper" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
rust = "latest"
go = "latest"
java = "21"

[settings]
experimental = true
