[env]
_.file = '.env'

[tools]
node = "latest"
python=['3.12','3.11']
"npm:dotenv" = "latest"
"npm:prettier" = "latest"
"npm:pnpm" = "latest"
"npm:git-cz" = "latest"
"npm:eslint" = "latest"
rust = "latest"
pnpm = "latest"
go = "latest"

[settings]
experimental = true
